/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())


    val c = new ConjDifusos()

    val mma = c.muchoMayorQue(3, 10)(8)
    val  mma2 = c.muchoMayorQue(1,9)(5)

    
    println(mma)
    println(mma2)


    //prueba de grade
    val g = c.grande(2, 6)(5)
    println(g)

    val m= c.muchoMayorQue(3, 10)(8)
    print(m)

    //prueba de complemento
    val comp = c.complemento(c.muchoMayorQue(3, 10))(8)
    println(comp) 

    
  }

  def greeting(): String = "Hello, world!"
}
