/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())


    val c = new ConjDifusos()

    val mma = c.muchoMayorQue(3, 10)(8)
    val  mma2 = c.muchoMayorQue(1,9)(5)

    
    println(mma)
    println(mma2)


    //prueba de grade
    val g = c.grande(2, 6)(5)
    println(g)

    val m= c.muchoMayorQue(3, 10)(8)
    print(m)

    //prueba de complemento
    val comp = c.complemento(c.muchoMayorQue(3, 10))(8)
    println(comp) 

    println("----------------------------"*5)
    val matriz = new Taller3()

    val m1 = matriz.matrizAlAzar(4, 10)
    val m2 = matriz.matrizAlAzar(4, 10)
    val m3 = matriz.resMatriz(m1, m2)
    val m4 = matriz.resMatriz(m1, m2)
    val m5 = matriz.multStrassen(m1, m2)
    val m6 = matriz.multMatriz(m1, m2)
    println(m1)
    println(m2)
    println(m3)
    println(m4)
    println(m5)
    println(m6)

    
  }

  def Benchmark(): Unit = {
    println("Benchmark")
  }

  def greeting(): String = "Hello, world!"
}
